### PR TITLE
Add Option to use dynamic physics-based animations (close #44)

### LINKED ISSUE #44: Try Physics-based Animations
What is the [Physics-based Animations](https://developer.android.com/topic/libraries/support-library/preview/physics-based-animation.html)
To solve #19

### PR DESCRIPTION
**Pull request by geecko86**
Alright, I found a solution to correctly track velocity: you had to get the rawX and rawY coordinates from the motionevent.

1. I added a new dependency: [support-dynamic-animation](https://developer.android.com/topic/libraries/support-library/preview/physics-based-animation.html) **NOTE:** the minsdk for the library is still 14 but no change will be visible when using the lib on API < 16.
2. I added an option (in the library and in the sample) to use Physics when throwing the FloatingView
3. I added another option so that the FloatingView would go to the side where it is thrown. Formerly if it was on the left of the screen and you lifted your finger, it would go back to the left side. Now, if you throw it to the right with enough speed, it will go to the right side, etc.

Here's a video to demonstrate it. The one with the mail icon is the one with the custom options.
➡➡➡ https://vid.me/SJvh

And here's two screenshots from the options
 

This does **NOT** in my opinon, solve issue #19.

### CODE REVIEW

**Comment by geecko86** [comment]
Perhaps it's more visible in this video, which shows my gestures:
https://vid.me/CHnf

**Comment by YoshihideSogawa** [comment]
Thank you for a wonderful feature.
However, we are currently testing to merge the develop branch into master.
There are probably conflicts because many modifications are done in the develop branch.
Please wait for the time being.

**Comment by geecko86** [comment]
Made a quick fix to remove all conflicts. Tell me what you think.

**Comment by geecko86** [comment]
Also, you guys might want to know that this library has been in use in production for my app "QuickLyric" for a few weeks now.

Screenshot

**Comment by geecko86** [comment]
Are you guys planning on merging this?

**Comment by YoshihideSogawa** [comment]
I am sorry to have kept you waiting. 
I will check as soon as possible.

**Comment by tiendung717** [comment]
Hi,
This feature is amazing.. Please spend your time to merge it to master.

**Pull request merged**
